#!/bin/bash
# cloud-init custom_data for the Airflow VM (vm.tf). Rendered by Terraform's
# templatefile(), so every $${...} below except $${docker_compose_content} is
# a Terraform variable substituted before this script ever runs; everything
# else is plain bash using $VAR (no braces) to avoid colliding with that.
set -euxo pipefail

ADMIN_USER="${admin_username}"
KEY_VAULT_NAME="${key_vault_name}"
POSTGRES_SECRET_NAME="${postgres_secret_name}"
STORAGE_ACCOUNT_NAME="${storage_account_name}"
DAGS_CONTAINER_NAME="${dags_container_name}"
LOGS_CONTAINER_NAME="${logs_container_name}"

AIRFLOW_DIR=/opt/airflow

# --- Docker Engine + Compose plugin -----------------------------------------
apt-get update
apt-get install -y ca-certificates curl gnupg jq
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
usermod -aG docker "$ADMIN_USER"

# --- Azure CLI, authenticated as the VM's system-assigned managed identity --
# Already granted Key Vault "Get/List" (keyvault.tf) and "Storage Blob Data
# Contributor" (storage.tf) — no credentials are embedded in this script.
curl -sL https://aka.ms/InstallAzureCLIDeb | bash
az login --identity --allow-no-subscriptions

# --- Airflow runtime dir (bind-mounted whole into the containers) ----------
mkdir -p "$AIRFLOW_DIR"/dags "$AIRFLOW_DIR"/tasks "$AIRFLOW_DIR"/logs
chown -R 50000:0 "$AIRFLOW_DIR"

# --- Metadata DB connection string, pulled from Key Vault -------------------
SQL_ALCHEMY_CONN=$(az keyvault secret show \
  --vault-name "$KEY_VAULT_NAME" \
  --name "$POSTGRES_SECRET_NAME" \
  --query value -o tsv)

cat > "$AIRFLOW_DIR/.env" <<ENV_EOF
AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$SQL_ALCHEMY_CONN
ENV_EOF
chmod 600 "$AIRFLOW_DIR/.env"

# --- docker-compose.yml, rendered from docker-compose.yml (repo root) ------
cat > "$AIRFLOW_DIR/docker-compose.yml" <<'COMPOSE_EOF'
${docker_compose_content}
COMPOSE_EOF

# --- DAG/task sync down from Blob, log sync up to Blob ----------------------
# Upload dags/ and tasks/ into the "dags" container using the same relative
# paths (e.g. blob "dags/demo_job.py", "tasks/create_ddl.py") so
# download-batch reconstructs them under $AIRFLOW_DIR correctly.
cat > /usr/local/bin/airflow-blob-sync.sh <<SYNC_EOF
#!/bin/bash
set -euo pipefail
az storage blob download-batch \
  --account-name "$STORAGE_ACCOUNT_NAME" \
  --auth-mode login \
  --source "$DAGS_CONTAINER_NAME" \
  --destination "$AIRFLOW_DIR" \
  --overwrite true >/var/log/airflow-blob-sync.log 2>&1

az storage blob upload-batch \
  --account-name "$STORAGE_ACCOUNT_NAME" \
  --auth-mode login \
  --destination "$LOGS_CONTAINER_NAME" \
  --source "$AIRFLOW_DIR/logs" \
  --overwrite true >>/var/log/airflow-blob-sync.log 2>&1
SYNC_EOF
chmod +x /usr/local/bin/airflow-blob-sync.sh

cat > /etc/systemd/system/airflow-blob-sync.service <<'UNIT_EOF'
[Unit]
Description=Sync Airflow DAGs down from / logs up to Blob Storage

[Service]
Type=oneshot
ExecStart=/usr/local/bin/airflow-blob-sync.sh
UNIT_EOF

cat > /etc/systemd/system/airflow-blob-sync.timer <<'TIMER_EOF'
[Unit]
Description=Run airflow-blob-sync every 3 minutes

[Timer]
OnBootSec=30s
OnUnitActiveSec=3min

[Install]
WantedBy=timers.target
TIMER_EOF

systemctl daemon-reload
systemctl enable --now airflow-blob-sync.timer

# Prime dags/tasks once before the first container start.
/usr/local/bin/airflow-blob-sync.sh || true

# --- Bring up the stack ------------------------------------------------
cd "$AIRFLOW_DIR"
docker compose up -d

# Admin login for the webserver UI is auto-generated by Airflow's default
# Simple Auth Manager on first start and written to
# /opt/airflow/simple_auth_manager_passwords.json.generated (same convention
# as the local venv setup in README.md) — read it over SSH, it is never
# passed through Terraform state or cloud-init logs.
