#!/bin/bash
# cloud-init custom_data for the Airflow VM (vm.tf). Rendered by Terraform's
# templatefile(), so every $${...} below except $${docker_compose_content} is
# a Terraform variable substituted before this script ever runs; everything
# else is plain bash using $VAR (no braces) to avoid colliding with that.
set -euxo pipefail

ADMIN_USER="${admin_username}"
KEY_VAULT_NAME="${key_vault_name}"
POSTGRES_SECRET_NAME="${postgres_secret_name}"

AIRFLOW_DIR=/opt/airflow

# --- Docker Engine + Compose plugin -----------------------------------------
apt-get update
apt-get install -y ca-certificates curl gnupg jq
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
usermod -aG docker "$ADMIN_USER"

# --- Azure CLI, authenticated as the VM's system-assigned managed identity --
# Already granted Key Vault "Get/List" (keyvault.tf) and "Storage Blob Data
# Contributor" (storage.tf) — no credentials are embedded in this script.
curl -sL https://aka.ms/InstallAzureCLIDeb | bash
az login --identity --allow-no-subscriptions

# --- Airflow runtime dir (bind-mounted whole into the containers) ----------
mkdir -p "$AIRFLOW_DIR"/dags "$AIRFLOW_DIR"/tasks "$AIRFLOW_DIR"/logs
chown -R 50000:0 "$AIRFLOW_DIR"

# --- Metadata DB connection string, pulled from Key Vault -------------------
SQL_ALCHEMY_CONN=$(az keyvault secret show \
  --vault-name "$KEY_VAULT_NAME" \
  --name "$POSTGRES_SECRET_NAME" \
  --query value -o tsv)

cat > "$AIRFLOW_DIR/.env" <<ENV_EOF
AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$SQL_ALCHEMY_CONN
ENV_EOF
chmod 600 "$AIRFLOW_DIR/.env"

# --- docker-compose.yml, rendered from docker-compose.yml (repo root) ------
cat > "$AIRFLOW_DIR/docker-compose.yml" <<'COMPOSE_EOF'
${docker_compose_content}
COMPOSE_EOF

# --- Bring up the stack ------------------------------------------------
cd "$AIRFLOW_DIR"
docker compose up -d

# Admin login for the webserver UI is auto-generated by Airflow's default
# Simple Auth Manager on first start and written to
# /opt/airflow/simple_auth_manager_passwords.json.generated (same convention
# as the local venv setup in README.md) — read it over SSH, it is never
# passed through Terraform state or cloud-init logs.
